// Exec Brief — No BYOK Required
// Verifies the 6-section executive brief generates deterministically
// without any AI provider configured. No BYOK key needed.

import { buildCommandCenterFactPack, generateWeeklyBrief, CommandCenterContext } from '../commandCenterService';
import { generateUltimateDemo, computeDemoCoverage } from '../ultimateDemoGenerator';
import { DEFAULT_PACK_CONFIG } from '../../types/demoTypes';
import { runPreMortemBatch } from '../preMortemService';

describe('Exec Brief without BYOK', () => {
  let brief: string;

  beforeAll(() => {
    const bundle = generateUltimateDemo('exec-no-byok', DEFAULT_PACK_CONFIG);
    const coverage = computeDemoCoverage(bundle);
    const ctx = buildDemoContext(bundle, coverage);
    const pack = buildCommandCenterFactPack(ctx);
    brief = generateWeeklyBrief(pack, 'Test Org');
  });

  it('generates without calling any AI service', () => {
    // If we got here, no AI call was made — the function is synchronous
    expect(brief).toBeTruthy();
    expect(brief.length).toBeGreaterThan(200);
  });

  it('contains all 6 section headers', () => {
    expect(brief).toContain('### 1. What needs attention');
    expect(brief).toContain('### 2. Are we on track?');
    expect(brief).toContain("### 3. What's at risk");
    expect(brief).toContain('### 4. What changed this week');
    expect(brief).toContain('### 5. What-if scenarios');
    expect(brief).toContain('### 6. Binding constraint');
  });

  it('includes org name in title', () => {
    expect(brief).toContain('# Weekly TA Brief — Test Org');
  });

  it('includes KPI table', () => {
    expect(brief).toContain('| KPI | Value | Target | Status |');
  });

  it('includes a verdict', () => {
    expect(brief).toMatch(/Verdict: (ON TRACK|AT RISK|OFF TRACK)/);
  });

  it('includes bottleneck diagnosis', () => {
    expect(brief).toMatch(/Diagnosis: (PIPELINE-BOUND|CAPACITY-BOUND|BOTH|HEALTHY)/);
  });

  it('does not contain "undefined" or placeholder values', () => {
    expect(brief).not.toContain('undefined');
    expect(brief).not.toContain('[object Object]');
    expect(brief).not.toContain('null');
  });

  it('ends with confidence footer', () => {
    expect(brief).toContain('_Generated by PlatoVue');
    expect(brief).toMatch(/Confidence: (HIGH|MED|LOW)/);
  });

  it('is valid markdown (has headers, lists, tables)', () => {
    // Has at least one header
    expect(brief).toMatch(/^#/m);
    // Has at least one list item
    expect(brief).toMatch(/^- /m);
    // Has at least one table row
    expect(brief).toMatch(/\|.*\|.*\|/);
  });
});

// ── Helper ─────────────────────────────────

function buildDemoContext(
  bundle: ReturnType<typeof generateUltimateDemo>,
  coverage: ReturnType<typeof computeDemoCoverage>
): CommandCenterContext {
  const { requisitions, candidates, events, users } = bundle;
  const preMortems = runPreMortemBatch(requisitions, candidates as any, events, []);

  const overview = {
    medianTTF: 35,
    totalOffers: candidates.filter(c => c.offer_extended_at).length,
    totalOfferAcceptanceRate: 0.85,
    totalHires: candidates.filter(c => c.hired_at).length,
    totalRequisitions: requisitions.length,
    totalCandidates: candidates.length,
    activePipeline: candidates.filter(c => !c.hired_at && !c.rejected_at && !c.withdrawn_at).length,
  } as any;

  const config = {
    version: '1.0',
    lastUpdated: new Date(),
    lastUpdatedBy: 'test',
    stageMapping: {},
    thresholds: { stalledDays: 14, zombieDays: 30 },
  } as any;

  return {
    requisitions,
    candidates: candidates as any,
    events,
    users,
    overview,
    hmFriction: [],
    actions: [],
    preMortems,
    filters: { dateRange: { start: null, end: null } },
    config,
    coverage,
  };
}
